import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import { lightColors, darkColors } from './colors';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: lightColors.primary,
    primaryContainer: lightColors.accentBackground,
    secondary: lightColors.secondary,
    secondaryContainer: lightColors.surfaceVariant,
    tertiary: lightColors.accent,
    tertiaryContainer: lightColors.accent2,
    background: lightColors.background,
    surface: lightColors.surface,
    surfaceVariant: lightColors.surfaceVariant,
    surfaceDisabled: lightColors.muted,
    error: lightColors.error,
    errorContainer: lightColors.error + '20',
    onPrimary: lightColors.primaryForeground,
    onPrimaryContainer: lightColors.accentForeground,
    onSecondary: lightColors.secondaryForeground,
    onSecondaryContainer: lightColors.text,
    onTertiary: lightColors.sidebarForeground,
    onTertiaryContainer: lightColors.text,
    onBackground: lightColors.foreground,
    onSurface: lightColors.foreground,
    onSurfaceVariant: lightColors.textSecondary,
    onError: '#ffffff',
    onErrorContainer: lightColors.error,
    outline: lightColors.border,
    outlineVariant: lightColors.border,
    inverseSurface: lightColors.surface,
    inverseOnSurface: lightColors.foreground,
    inversePrimary: lightColors.primary,
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  roundness: 10,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkColors.primary,
    primaryContainer: darkColors.accentBackground,
    secondary: darkColors.secondary,
    secondaryContainer: darkColors.surfaceVariant,
    tertiary: darkColors.accent,
    tertiaryContainer: darkColors.accent2,
    background: darkColors.background,
    surface: darkColors.surface,
    surfaceVariant: darkColors.surfaceVariant,
    surfaceDisabled: darkColors.muted,
    error: darkColors.error,
    errorContainer: darkColors.error + '20',
    onPrimary: darkColors.primaryForeground,
    onPrimaryContainer: darkColors.accentForeground,
    onSecondary: darkColors.secondaryForeground,
    onSecondaryContainer: darkColors.text,
    onTertiary: darkColors.sidebarForeground,
    onTertiaryContainer: darkColors.text,
    onBackground: darkColors.foreground,
    onSurface: darkColors.foreground,
    onSurfaceVariant: darkColors.textSecondary,
    onError: '#ffffff',
    onErrorContainer: darkColors.error,
    outline: darkColors.border,
    outlineVariant: darkColors.border,
    inverseSurface: darkColors.surface,
    inverseOnSurface: darkColors.foreground,
    inversePrimary: darkColors.primary,
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  roundness: 10,
};

